#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
  # config::check_or_set $1 $2 $SERVICE_CONFIG "$3" "$4" $5
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  service::config_set SERVICE_MEMOS_SECRET_KEY text "Secret Key:" "$(os::random_string 8)"
}

check $@
